name = "Retention Engine"
client_id = "394f71297286a115d71051f424664ff8"
application_url = "https://shopify-retention-app-production.up.railway.app"
embedded = true

[access_scopes]
scopes = "read_customers,read_orders"

[auth]
redirect_urls = [
  "https://shopify-retention-app-production.up.railway.app/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false